CREATE DATABASE db;

\c db

-- SETING TIMEZONE TO UTC
SET timezone = 'UTC';

CREATE TABLE IF NOT EXISTS migrations (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATING ITEMS TABLE
CREATE TABLE IF NOT EXISTS items(
  id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(80) NOT NULL,
  description VARCHAR(255),
  price NUMERIC(10,2) NOT NULL,
  quantity SMALLINT NOT NULL DEFAULT 0
);

-- CREATING CLIENTS TABLE
CREATE TABLE IF NOT EXISTS clients(
  id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(80) NOT NULL,
  email VARCHAR(80) NOT NULL,
  UNIQUE (email)
);

-- CREATING ORDERS TABLE
CREATE TABLE IF NOT EXISTS orders(
  id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID REFERENCES clients(id) NOT NULL,
  observation VARCHAR(255), 
  status SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  CONSTRAINT status_check CHECK (status >= 0 AND status <= 5)
);

CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

-- CREATING ORDER ITEMS TABLE
CREATE TABLE IF NOT EXISTS order_items(
  id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID REFERENCES orders(id) NOT NULL,
  item_id UUID REFERENCES items(id) NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  quantity SMALLINT NOT NULL
);